### PR TITLE
Create/Update the Upgrade 4.x doc

### PR DESCRIPTION
**Pull request by BloodStoneBBS**
and Plagiarize where obvious ;-)
This looks a lot better than my previous attempt.

### CODE REVIEW

**Comment by askpatrickw** [comment]
I read this over and I think it only explains a clean install. I'm not sure what I should do with the 4.x files. For instance, If I had a 4.x install in c:\MyBSSRulz...  Should they copy of the top of 4.x? Should they copy certain sub directories form 4.x over the top of the clean install of 5.0 in \wwiv?  

NOTE: I don't have any 4.x files and I have no idea what the right steps are.

**Comment by BloodStoneBBS** [comment]
That makes sense. I'll try and update this some more soon to be more specific about the file locations etc.. It is more or less drop & go aside for updating the wwiv.ini.

**Comment by BloodStoneBBS** [comment]
Resubmitted as a new pull. Look better?

Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by askpatrickw** [comment]
Looking good, one thing. Don't use full URLs to pages, just the filename. If you use full URLs, when we version the docs there URLs will break because your URLs will only point to latest, but we'll have 5.0 and 5.1 URLs at some point. The tools that generate the html take career of that for us.

Other than that, looks great.

**Comment by askpatrickw** [comment]
I'm at my keyboard now(was on my phone earlier). I'll merge this and fix the urls. Thanks a lot!

**Comment by BloodStoneBBS** [comment]
Thanks. Happy to help!

Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Pull request merged**
